implement standard solana wallet functionality (#12)

diff --git a/provision b/provision
--- a/provision
+++ b/provision
@@ -2,27 +2,49 @@
 
 #    laurelin-wallet --config ~/.laurelin/$i/config.json --wallet ~/.laurelin/$i/wallet.json pubkey | grep Solana | awk '{print $3}'
 
+n=4
+if [ -n "$1" ]; then
+    n="$1"
+fi
+
+base="$HOME/.laurelin"
+if [ -n "$2" ]; then
+    if [ "$2" = "$HOME" ]; then
+        echo "can't use $HOME as the base path"
+        exit 1
+    fi
+    base="$2"
+fi
+
+program=4eesfezqbNcYSJLmQqvxN38CdsccYGFYUaZdBgQp7a2L
+pk_dir=/Users/axoloki/src/laurelin/circuit/setup
+
 laurelin() {
     j=$1
     shift
-    laurelin-wallet --config ~/.laurelin/$j/config.json --wallet ~/.laurelin/$j/wallet.json $@
+    laurelin-wallet --config "$base/$j/config.json" --wallet "$base/$j/wallet.json" $@
 }
 
-if [ "$1" = 'bn254' ]; then
-    laurelin 1 pubkey | grep BN254 | awk '{print $4}'
-    exit
-fi
-
-for ((i=1; i<=$1; i++)); do
+rm -rf "$base"
+for ((i=1; i<=$n; i++)); do
     echo "run iteration $i"
-    rm -rf  ~/.laurelin/$i
     laurelin $i init --insecure
-    laurelin $i config set-program 4eesfezqbNcYSJLmQqvxN38CdsccYGFYUaZdBgQp7a2L
-    laurelin $i config set-pk-dir /Users/axoloki/src/laurelin/circuit/setup
+    laurelin $i config set-program "$program"
+    laurelin $i config set-pk-dir "$pk_dir"
 
-    export pubkey=`laurelin $i pubkey | grep Solana | awk '{print $3}'`
+    export pubkey=`laurelin $i pubkey --sol`
     echo "Solana pubkey is $pubkey"
     solana airdrop 100 "$pubkey" --url localhost
 
     laurelin $i create-account
 done
+
+laurelin-wallet init
+laurelin-wallet config set-program "$program"
+laurelin-wallet config set-pk-dir "$pk_dir"
+
+export pubkey=`laurelin-wallet pubkey --sol`
+echo "Solana pubkey is $pubkey"
+solana airdrop 100 "$pubkey" --url localhost
+
+laurelin-wallet create-account
